### ISSUE TITLE
cba_budget_account enhancement to use template tags like  login names {co}

### ISSUE THREAD

**Issue by basvandervlies** [SURFscz/SRAMsync#82]
This is now hardcoded
```
cba_budget_account: jhldem001
```

would be nice to use for example `{co{}`:
```
cba_budget_account: {co}
```

**Comment by FlorisFokkinga** [comment]
SBS uses the `{CO_short_name}` template tag for other purposes, consider using the same name.

**Comment by basvandervlies** [comment]
Just tried `{CO_short_name}` for `CbaScriptGenerator` and `CUA` but this is not recognized as keyword. I do not know what the standard is or will be. But it would be nice to use the same tags.

**Comment by venekamp** [comment]
Indeed, might be a good idea to indicate the CO short name from SRAM is used.

**Comment by venekamp** [comment]
@basvandervlies I try to understand what it is you are precisely asking. I keep failing :-( Let's set together and we have fixed the misunderstanding in five minutes or less :-)

**Comment by basvandervlies** [comment]
It is not that difficult we have multiple co's and the budget account is hardcoded is wo not work just like:
```
    rename_user:                                                                                                                                                                     
         default: "{co}-{uid}"                                                                                                                                                       
         groups:                                                                                                                                                                     
            surfjupytertest_teacher: "{co}-{uid}-teacher"                                                                                                                            
            surfjupytertest_student: "{co}-{uid}"  
```

we want that the `cba_budget_account` also use this template tag `{co}`

Then it will scale out for all the CPU based jupyterhub courses
